### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by Reksa4real** [nicksuperiorservers/loggingSuite#5]
So like I was entering a log then I accidentally hit enter instead of shift so I was brought up to the spell check window and tried to cancel that so I can continue writing my log which does not work because it sends it any. Also, why is it that if your log is big enough not all of it will appear on the form. what's up w that?

**Comment by Nicks-Alt** [comment]
You can always go back and edit your logs by just selecting the day and entering a new one.
